[program:ordersaif-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/ordersaif.com/deploy/current/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=ordersaif
numprocs=4
redirect_stderr=true
stdout_logfile=/home/ordersaif.com/deploy/shared/worker.log
stopwaitsecs=3600
